import {IStoriesBlockResponse} from "@/types/stories.types.ts";

export const mockedStories: IStoriesBlockResponse[] = [{
    "name": "1AASDffff",
    "active": true,
    "thumbnail": "asda",
    "cities": [2],
    "users": [],
    "priority": 0,
    "views_count": 0,
    "id": 62,
    "stories": []
}, {
    "name": "Екатеринбург + СПб + mp4 (не редактируем)",
    "active": true,
    "thumbnail": "https://storage.yandexcloud.net/bottec-dreamteam/8c418ae16cdb4692876f510c7e447795.blob",
    "cities": [2, 3],
    "users": [],
    "priority": 0,
    "views_count": 0,
    "id": 60,
    "stories": [{
        'type': 'video',
        'duration': 5500,
        'url': 'https://drive.google.com/uc?export=download&id=1VO1SPRZGEboZ8VSNTs_aWOn3UtYUn6Zz',
        'title': null,
        'description': null,
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 1,
        'views_count': 0,
        'id': 57,
        'component_type': 1,
    }, {
        'type': 'component',
        'duration': 6000,
        'url': null,
        'title': 'Екатеринбург и Санкт-Петербург',
        'description': 'далее видео mp4',
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 2,
        'views_count': 0,
        'id': 56,
        'component_type': null,
    }]
}, {
    "name": "СПб + видео (не редактируем)",
    "active": true,
    "thumbnail": "https://storage.yandexcloud.net/bottec-dreamteam/3cd09fa82c274f4cbb16b1e13815115d.blob",
    "cities": [2],
    "users": [],
    "priority": 0,
    "views_count": 0,
    "id": 59,
    "stories": [{
        'type': 'component',
        'duration': 5000,
        'url': null,
        'title': 'Блок должен быть доступен в Санкт-Петербурге',
        'description': 'Дальше видео (blob)',
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 1,
        'views_count': 0,
        'id': 54,
        'component_type': null,
    }, {
        'type': 'video',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/6282d4afc41f4771b03a0cbf830f1f10.mp4',
        'title': null,
        'description': null,
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 2,
        'views_count': 0,
        'id': 55,
        'component_type': null,
    }]
}, {
    "name": "Москва + Питер (не редактируем)",
    "active": true,
    "thumbnail": "https://storage.yandexcloud.net/bottec-dreamteam/8053b0d5d02d4bde835bc26c43607040.blob",
    "cities": [1, 2],
    "users": [],
    "priority": 0,
    "views_count": 0,
    "id": 54,
    "stories": [{
        'type': 'component',
        'duration': 5000,
        'url': null,
        'title': 'Здесь только Title',
        'description': null,
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 1,
        'views_count': 0,
        'id': 39,
        'component_type': null,
    }, {
        'type': 'component',
        'duration': 5000,
        'url': null,
        'title': 'Здесь Title',
        'description': 'и описание',
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 2,
        'views_count': 0,
        'id': 40,
        'component_type': null,
    }, {
        'type': 'component',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/744ae33c0b654c42b251597d8cabf462.blob',
        'title': 'Здесь Title',
        'description': 'и описание с изображением',
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 3,
        'views_count': 0,
        'id': 41,
        'component_type': 1,
    }, {
        'type': 'component',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/269c76c1d18345d68f77e64b4a832f03.blob',
        'title': 'А здесь',
        'description': 'история с вертикальным изображением',
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 4,
        'views_count': 0,
        'id': 42,
        'component_type': 2,
    }, {
        'type': 'component',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/0611127c22b5461aa17f5be133ecd999.blob',
        'title': 'Заголовок',
        'description': 'описание, а ниже кнопка!',
        'button_url': 'https://dropmefiles.com/',
        'button_text': 'Open dropmefiles',
        'button_color': '#214f2d',
        'order_index': 5,
        'views_count': 0,
        'id': 43,
        'component_type': 1,
    }, {
        'type': 'component',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/bbfa3054813240449b360d5eb2e584f7.blob',
        'title': null,
        'description': null,
        'button_url': 'https://dropmefiles.com/',
        'button_text': 'Open DropMeFiles',
        'button_color': '#f3c481',
        'order_index': 6,
        'views_count': 0,
        'id': 44,
        'component_type': 2,
    }, {
        'type': 'image',
        'duration': 8000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/021bd794c6dc44b3ba5525add00c1519.blob',
        'title': null,
        'description': null,
        'button_url': null,
        'button_text': null,
        'button_color': null,
        'order_index': 7,
        'views_count': 0,
        'id': 46,
        'component_type': null,
    }, {
        'type': 'image',
        'duration': 6000,
        'url': 'https://storage.yandexcloud.net/bottec-dreamteam/8fdf993c577343f5a271bcbb7da9cee0.blob',
        'title': 'string',
        'description': 'string',
        'button_url': 'string',
        'button_text': 'string',
        'button_color': 'string',
        'order_index': 8,
        'views_count': 0,
        'id': 45,
        'component_type': null,
    }]
}]
